### ISSUE TITLE
Reader area - out of rectangle

### ISSUE THREAD

**Issue by lucamancusodev** [iemadk/BarCode-reader#1]
Hi,
We found that during the reading, the barcode area is not only in the rectangle but in all the camera view area.
Is there any configuration that can be tweaked?

Thanks

**Comment by andriux1990** [comment]
I clone the project but it doesn't work for me .. what did you do to make it work for you?

**Comment by lucamancusodev** [comment]
> 
> 
> I clone the project but it doesn't work for me .. what did you do to make it work for you?

Do you see any error in console log?
Remember that the live reader works only in https.
